p(aarav,abhay).
p(aarav,sameeksha).
p(aarvi,arika).
p(aarvi,shaurya).
p(ashok,aarav).
p(ashok,aarvi).
gp(ashok,abhay).
gp(ashok,sameeksha).
gp(ashok,arika).
gp(ashok,shaurya).
male(ashok).
male(aarav).
male(abhay).
male(shaurya).
female(sameeksha).
female(arika).
female(aarvi).
sibling(aarav,aarvi).
sibling(abhay,sameeksha).
sibling(arika,shaurya).